### ISSUE TITLE
Make the file parsing process a public function.

### ISSUE THREAD

**Issue by zztkm** [zztkm/vdotenv#12]
**Describe the solution you'd like**
I want to incorporate the file parse process into the library as a public function

**Comment by nyx-litenite** [comment]
I can make a draft PR when i get off work, but I'm going to take a crack at multiline values as well. That will probably require a bit of refactoring in parsing.

**Comment by nyx-litenite** [comment]
Just to clarify, by this: "incorporate the file parse process", you mean like the function from the link in the other issue (https://github.com/bkeepers/dotenv#parsing)?

**Comment by zztkm** [comment]
Yes, that's right

**Comment by nyx-litenite** [comment]
Ok then it should be covered in what I've got so far. Only change would probably occur when multiline is implemented

**Comment by zztkm** [comment]
Multiline is not yet implemented in my perception.

**Comment by nyx-litenite** [comment]
Correct, i was saying that multiline would affect parsing when it was implemented. I'm working on multiline as well. I've got it basically working [w/ parsing], but it may take a bit of more work.

**Comment by zztkm** [comment]
@nyx-litenite 

I'm sorry for the late reply.


>  I'm working on multiline as well. I've got it basically working [w/ parsing], but it may take a bit of more work.
How much progress are you currently making?
I haven't worked on multiline yet...

**Comment by nyx-litenite** [comment]
No worries. I wasn't going to tackle it, but comments and parsing were kind of related to multi line, so i started taking a peek. I have a good bit of it finished, but I got a little busy over the last couple days. I was going to look into it  a bit more now that I've got a bit more time

**Comment by nyx-litenite** [comment]
Parsing should be fully implemented [here](https://github.com/zztkm/vdotenv/pull/17) (at least my understanding of the hash; let me know if something else is prefered). Multiline isn't implemented, but I don't think it will actually affect the public parsing as much as I once thought.

**Comment by zztkm** [comment]
I think [this implementation](https://github.com/zztkm/vdotenv/pull/17) is probably fine.
