### ISSUE TITLE
getting error in v.02

### ISSUE THREAD

**Issue by chovy** [zztkm/vdotenv#15]
```
$ v -v       
V 0.2.1 681ff3c
```

```
import zztkm.vdotenv
fn main() {
  vdotenv.load()
  println(os.getenv('DB_FILE'))
}
```

I get the following error.

```
V panic: array.get: index out of range (i == 1, a.len == 1)
/tmp/v/app.7487424161921400127.tmp.c:7099: at v_panic: Backtrace
/tmp/v/app.7487424161921400127.tmp.c:6618: by array_get
/tmp/v/app.7487424161921400127.tmp.c:15096: by zztkm__vdotenv__parse_lines
/tmp/v/app.7487424161921400127.tmp.c:15065: by zztkm__vdotenv__parse_contents
/tmp/v/app.7487424161921400127.tmp.c:15119: by zztkm__vdotenv__load_env
/tmp/v/app.7487424161921400127.tmp.c:14979: by zztkm__vdotenv__load
/tmp/v/app.7487424161921400127.tmp.c:18484: by main__main
/tmp/v/app.7487424161921400127.tmp.c:18700: by main

```

**Comment by zztkm** [comment]
Thank you for your report!

This issue will be resolved later this week.

We apologize for the inconvenience, but please wait.

**Comment by nyx-litenite** [comment]
@chovy , it'd be useful if we could get an example of your .env file. 
I suspect it has something to do w/ these lines from vdotenv.v (line 122+)

``` v
mut new_line := segments_to_keep.join('#')
key := new_line.split('=')[0].trim_space()
value := new_line.split('=')[1].trim_space()
```
since we don't actually verify that a value exists for a key before trying to access the array

**Comment by chovy** [comment]
Here is my `.env`

```
PORT=8023

# environment
HOST_USER=ubuntu
HOST_DOMAIN=profullstack
HOST_PATH=svelteweekly.com
HOST_PROJECT=svelteweekly-api

DB_FILE=emailstest.txt
ZENSERP_KEY=622-f960098b110c
```

**Comment by nyx-litenite** [comment]
Thanks :+1: Could you try without the empty line and see if works then?

**Comment by nyx-litenite** [comment]
forget that scrolled up and saw that the Port setting was followed by an empty line. Are you able to access any of the other fields or do they all fail?

**Comment by nyx-litenite** [comment]
Ah, as I suspected; it is the empty lines. For now, we don't support empty lines in the .env, so either remove those or place a `#` as a placeholder. This may change eventually, but is not slated now.

**Comment by chovy** [comment]
oh wow. that seems like an oversight. can't you just skip lines that are empty?

**Comment by nyx-litenite** [comment]
Idk if it was an oversight. I believe the library was originally just for personal use, so was probably tailored to what zztkm needed :) This should be resolved in my [PR](https://github.com/zztkm/vdotenv/pull/16) ; where I tell it to just ignore the empty lines as you suggested :) checkout my fork to use it directly (or just change `if !line.starts_with('#')` to `if !line.starts_with('#') && line.len > 0` in vdotenv.v line 105 ;)

**Comment by chovy** [comment]
that's cool. i'll wait, I may write a book about V so I'll add this module in it as I find it very useful for practical development.

**Comment by nyx-litenite** [comment]
Ya, I've always like the dotenv api and feel :) was really happy when I found someone else had ported to V

**Comment by zztkm** [comment]
@chovy @nyx-litenite 
Thank you for the wonderful discussion.

I also think I need to fix the blank lines to skip, so let's fix it!

**Comment by zztkm** [comment]
@nyx-litenite 
I checked the corrections and merged them!

@chovy 
Is it okay to close this issue?
